name: ci

on: [push, pull_request]

jobs:
  deno:
    name: publish-on-tag
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # - name: Format
      #   run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test -A

      - name: Publish on tag
        run: deno run -A jsr:@david/publish-on-tag@0.1.4
